# Generated by Django 5.2.7 on 2025-11-06 18:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_es', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
                ('iso_code', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('phone_code', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_country',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_es', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_event',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_es', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_status',
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_es', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('regex_pattern', models.CharField(blank=True, max_length=200, null=True)),
                ('min_length', models.IntegerField(default=1)),
                ('max_length', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_documents', to='core.country')),
                ('key_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_documents', to='core.status')),
            ],
            options={
                'db_table': 'core_identity_document',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_abbreviation', models.CharField(max_length=10)),
                ('event_name', models.CharField(max_length=100)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user_email', models.CharField(blank=True, max_length=150, null=True)),
                ('country_abbreviation', models.CharField(blank=True, max_length=5, null=True)),
                ('identity_document_abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('document', models.CharField(blank=True, max_length=50, null=True)),
                ('record_id', models.UUIDField(blank=True, null=True)),
                ('table_name', models.CharField(max_length=100)),
                ('module_name', models.CharField(max_length=100)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_log',
                'indexes': [models.Index(fields=['-created_at'], name='core_log_created_a7c779_idx'), models.Index(fields=['table_name'], name='core_log_table_n_d68c13_idx'), models.Index(fields=['record_id'], name='core_log_record__538add_idx'), models.Index(fields=['event_abbreviation'], name='core_log_event_a_7bb222_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('key_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.log')),
            ],
            options={
                'db_table': 'core_log_detail',
                'ordering': ['column_name'],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='key_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='core.status'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.CharField(max_length=50)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('key_identity_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.identitydocument')),
            ],
            options={
                'db_table': 'core_user',
                'constraints': [models.UniqueConstraint(fields=('key_identity_document', 'document'), name='uq_user_document_type')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='identitydocument',
            constraint=models.UniqueConstraint(fields=('abbreviation', 'key_country'), name='uq_identity_country'),
        ),
    ]
