# Generated by Django 5.2.7 on 2025-10-31 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_key_identity_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='regex_pattern',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_es', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.status')),
            ],
            options={
                'db_table': 'core_event',
                'unique_together': {('name_es', 'name_en')},
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_record', models.UUIDField()),
                ('name_table', models.CharField(max_length=100)),
                ('name_module', models.CharField(max_length=100)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.event')),
                ('key_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_log',
            },
        ),
        migrations.CreateModel(
            name='LogDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.log')),
            ],
            options={
                'db_table': 'core_log_detail',
                'ordering': ['column_name'],
            },
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-created_at'], name='core_log_created_a7c779_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['key_record'], name='core_log_key_rec_a18349_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['name_table'], name='core_log_name_ta_84dc92_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['key_user'], name='core_log_key_use_86e62e_idx'),
        ),
    ]
