# Generated by Django 5.2.7 on 2025-11-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_country_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='log',
            name='core_log_name_ta_84dc92_idx',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='name_module',
            new_name='module_name',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='name_table',
            new_name='table_name',
        ),
        migrations.RemoveField(
            model_name='logdetail',
            name='created_at',
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['table_name'], name='core_log_table_n_d68c13_idx'),
        ),
    ]
