# Generated by Django 5.2.7 on 2025-11-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_remove_log_core_log_name_ta_84dc92_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='identitydocument',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_es',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_en',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_es',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_en',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_es',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='identitydocument',
            constraint=models.UniqueConstraint(fields=('abbreviation', 'key_country'), name='uq_identity_country'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('key_identity_document', 'document'), name='uq_user_document_type'),
        ),
    ]
